### ISSUE TITLE
Compilation errors on apple-clang

### ISSUE THREAD

**Issue by toge** [lemire/FastPFor#120]
Thank you for releasing 0.2.0!
I met compilation error on Apple M1 with apple-clang.

```
[ 70%] Building CXX object CMakeFiles/FastPFOR.dir/src/simdbitpacking.cpp.o
[ 80%] Building CXX object CMakeFiles/FastPFOR.dir/src/simdunalignedbitpacking.cpp.o
error: unknown target CPU 'vortex'
note: valid target CPU values are: nocona, core2, penryn, bonnell, atom, silvermont, slm, goldmont, goldmont-plus, tremont, nehalem, corei7, westmere, sandybridge, corei7-avx, ivybridge, core-avx-i, haswell, core-avx2, broadwell, skylake, skylake-avx512, skx, cascadelake, cooperlake, cannonlake, icelake-client, icelake-server, tigerlake, sapphirerapids, alderlake, knl, knm, k8, athlon64, athlon-fx, opteron, k8-sse3, athlon64-sse3, opteron-sse3, amdfam10, barcelona, btver1, btver2, bdver1, bdver2, bdver3, bdver4, znver1, znver2, znver3, x86-64, x86-64-v2, x86-64-v3, x86-64-v4
make[2]: *** [CMakeFiles/FastPFOR.dir/src/simdbitpacking.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```

`error: unknown target CPU 'vortex'` seems to be caused by apple-clang bug.

Same problem has been reported in CMake.
https://gitlab.kitware.com/cmake/cmake/-/issues/22484
https://www.phoronix.com/news/LLVM-Clang-march-native-M1

I met same problems on apple-clang x86_64 build.
To fix these issues, I make a following patch.

```cmake
elseif(${CMAKE_CXX_COMPILER_ID} STREQUAL "Clang")
    if (CXX_COMPILER_VERSION VERSION_LESS 4.2.1)
        message(STATUS  "Clang version must be at least 4.2.1!" )
    endif()
    set (CMAKE_CXX_FLAGS_RELEASE "-Wall -Wcast-align -O3 -DNDEBUG -std=c++11 -DHAVE_CXX0X -march=native")
    set (CMAKE_CXX_FLAGS_DEBUG   "-Wall -Wcast-align -ggdb  -std=c++11 -DHAVE_CXX0X -march=native")
    set (CMAKE_C_FLAGS_RELEASE "-Wall -Wcast-align -O3 -DNDEBUG -std=c99 -march=native")
    set (CMAKE_C_FLAGS_DEBUG   "-Wall -Wcast-align -ggdb  -std=c99 -march=native")
elseif(${CMAKE_CXX_COMPILER_ID} STREQUAL "AppleClang")
    set(TUNE_FLAG "-mtune=core-avx2")
    if(CMAKE_OSX_ARCHITECTURES MATCHES "arm64.*")
        set(TUNE_FLAG "-mtune=apple-m1")
    endif()
    set (CMAKE_CXX_FLAGS_RELEASE "-Wall -Wcast-align -O3 -DNDEBUG -std=c++11 -DHAVE_CXX0X ${TUNE_FLAG}")
    set (CMAKE_CXX_FLAGS_DEBUG   "-Wall -Wcast-align -ggdb  -std=c++11 -DHAVE_CXX0X ${TUNE_FLAG}")
    set (CMAKE_C_FLAGS_RELEASE "-Wall -Wcast-align -O3 -DNDEBUG -std=c99 ${TUNE_FLAG}")
    set (CMAKE_C_FLAGS_DEBUG   "-Wall -Wcast-align -ggdb  -std=c99 ${TUNE_FLAG}")
```

Is it a valid way to solve these problems?

**Comment by lemire** [comment]
Our CI runs on macos-latest which is currently this system:

https://github.com/actions/runner-images/blob/main/images/macos/macos-14-arm64-Readme.md

I'm personally a macOS person and all my computers are macs.

The similar errors you are pointing at refer to old versions of LLVM.

Can you confirm that your system is up-to-date? You do not provide the necessary information.

Please make sure you are using LLVM 15 or better. We have not tested on legacy system.

**Comment by toge** [comment]
@lemire 
Thank you for quick response.

I am using apple-clang 16.0.0.
As you mentioned, version 0.2.0 works fine when I run cmake by hand.
Sorry for my lack of testing.

My problem occurred during the conan build process on apple-clang 16.0.0.
I think it is caused by the conan environment.
I'm going to ask conan's community.

Thanks!
