### ISSUE TITLE
make example dosen't work

### ISSUE THREAD

**Issue by jesusjzp** [lemire/FastPFor#18]
Hi @lemire , it seems that there is no more `example` in Makefile, or did I miss something? Thanks!

**Comment by lemire** [comment]
We have upgraded the build setup and it seems likely that the example will not build anymore according to the old instructions. This needs to be updated.

Sorry about the inconvenience.

**Comment by jesusjzp** [comment]
Thanks for the reply! Actually I can build `example.cpp` manually by `g++ -std=c++11 example.cpp libFastPFor.a -o example`.

**Comment by lemire** [comment]
@jesusjzp 

Exactly, but the make file should be able to do it for you. This is a bug.

**Comment by jesusjzp** [comment]
Thanks @lemire :blush:

**Comment by lemire** [comment]
Issue has been resolved.

See

https://github.com/lemire/FastPFor/commit/08c75db91e6b84611d4f91ba3212c4aec4f0e988

Reopen if you disagree.

**Comment by jesusjzp** [comment]
Yeah it works, thank you @lemire !
