### ISSUE TITLE
Add support for 64-bit integers

### ISSUE THREAD

**Issue by mtlmeijer** [lemire/FastPFor#23]
Adding this as an issue, it is mentioned in the TODO.md file.

We would like to compress 64 bit unsigned integers.
Since the library now requires a 64 bit system (see README.md), 64 bit compression would be useful.

**Comment by binmahone** [comment]
any updates on this? is there any recommended workarounds for 64 bit integers?

**Comment by lemire** [comment]
Publicly available datasets derived from actual problems would go a long way generating interest for this problem.

**Comment by lemire** [comment]
The FrameOfReference (C++) library supports compressing arrays of 64-bit values https://github.com/lemire/FrameOfReference

**Comment by rapoth** [comment]
Thank you for the great library. 

I see that the FrameOfReference repo you linked to does not have MSVC support etc. similar to FastPFor. Since I see that this thread has been open since 2015 I just wanted to check to see if you had any plans for adding support for 64-bit unsigned integers. Thank you!

**Comment by lemire** [comment]
@rapoth I think you should have no problem building FrameOfReference with Visual Studio if you follow these instructions...

https://github.com/lemire/FrameOfReference#building-visual-studio-under-windows

**Comment by rapoth** [comment]
@lemire I verified that the latest version is working on Windows. Thank you so much! I really appreciate your time.

**Comment by lemire** [comment]
@rapoth  ;-)

**Comment by lemire** [comment]
Resolved by @xndai via https://github.com/lemire/FastPFor/pull/58
