### ISSUE TITLE
Simple9_rle and simple8b_rle are disable because they do not pass unit tests

### ISSUE THREAD

**Issue by lemire** [lemire/FastPFor#25]
These codecs were contributed by @ncave  but, sadly, they do not appear to pass our unit tests.

They have been disabled and a warning has been added:

https://github.com/lemire/FastPFor/commit/a4418c093f1f54b2e61fd53fa16829d97d695c2c

@ncave? Can you have a look?

**Comment by lemire** [comment]
Note that I had to switch the order of the classes so that the code would build (I don't think C++ allows one to use a class before it has been declared)... see the reported error...

https://github.com/lemire/FastPFor/commit/30949d8b5eb4e0c4df0851f17cb237967f77ac53#commitcomment-13762587

**Comment by lemire** [comment]
I have added continuous integration support to this project via travis:

https://travis-ci.org/lemire/FastPFor

This should check any future PR.

**Comment by ncave** [comment]
Forgot to include in PR comment that https://github.com/lemire/FastPFor/commit/3cbb5f8c2dd06705ea2835dc93cadf2063b98b7b fixes #25, can you please close.

**Comment by lemire** [comment]
Resolved.
