### ISSUE TITLE
Multiple definition error on __builtin_clz() in MSVC

### ISSUE THREAD

**Issue by kimikage** [lemire/FastPFor#44]
In MSVC, the header file `util.h` defines a function `__builtin_clz()`.
Since it is not a inline function, a multiple definition error `LNK2005` can occur.
https://github.com/lemire/FastPFor/blob/d873fe18edf487ff7e4e737883e6f63a54a0a578/headers/util.h#L117-L126

A possible solution is adding the `inline` to the function:
```c++
inline uint32_t __builtin_clz(uint32_t x) {
```

**Comment by lemire** [comment]
Would you issue a PR? This way you get credit for your contribution.
