### ISSUE TITLE
You tried to apply Simple16 to an incompatible set of integers

### ISSUE THREAD

**Issue by pps83** [lemire/FastPFor#51]
https://github.com/lemire/FastPFor/blob/71d54a9793245ae90e69c86a425d4ee1ee6543d8/headers/simple16.h#L377

so, there is that exception, but no explanation at all what Simple16 considers incompatible.

Also, many codecs are plainly broken, read/write random memory or crash. These are buggy/broken: simple16, simple8b_rle, simple9, simple9_rle, vsencoding, simdfastpfor256, fastpfor128, fastpfor256, simdfastpfor128 (the last for read random memory here and there).

**Comment by lemire** [comment]
This should be better documented, but it should be clear from the code:

```C
if ((*in >> 28) > 0) {
        std::cerr << "Input's out of range: " << *in << std::endl;
        throw std::runtime_error(
            "You tried to apply Simple16 to an incompatible set of integers.");
 }
```

Integers are expected to be in [0, 2^28).

**Comment by lemire** [comment]
> Also, many codecs are plainly broken, read/write random memory or crash. These are buggy/broken: simple16, simple8b_rle, simple9, simple9_rle, vsencoding, simdfastpfor256, fastpfor128, fastpfor256, simdfastpfor128 (the last for read random memory here and there).

Can you open issues with each bug you have found with a reproducing test case? Ideally, please consider issue pull requests to fix the issues you have found.

**Comment by lemire** [comment]
Fixed as per...
https://github.com/lemire/FastPFor/commit/19c9e6e65d9879da22f8daa486decd6ba01bcf10

Regarding other issues you allude to, please open separate issues and provide reproducible test cases and/or factual analysis to describe the problem.

**Comment by pps83** [comment]
If all these simpleNN codecs fail because the inpunt numbers have different range, then this part is cleared.
Regarding simdfastpfor256, fastpfor128, fastpfor256, simdfastpfor128  (these seem to be high quality compressors), I only get errors in these if 1) I enable 32-bit build and, if 2) I redefine `__restrict__` to `__restrict` on VS (which is supported), and if 3) I run some code to compress large arrays with  [Dr.Memory](https://github.com/DynamoRIO/drmemory) (it's based on [DynamoRIO](https://en.wikipedia.org/wiki/DynamoRIO)).
Also many other codecs in my case required way more than 1KB extra space for them not to access random memory.

**Comment by lemire** [comment]
Sure... I trust that the issues you found are real. I am just inviting you to open distinct issues... (otherwise it is hard to keep track of what is what).

**Comment by pps83** [comment]
I tried to debug and it's not conclusive, I didn't see memory access issues. Without __restrict I didn't get any reported issues though, so hard to even report anything as __restrict isn't used on VS anyways.

**Comment by pps83** [comment]
Just wanted to let you know that results that I got from `FastPFor` overcame all my expectations. Awesome!
I made a few VS-related fixes and ported some codecs that were disabled for VS: https://github.com/lemire/FastPFor/pull/52

**Comment by lemire** [comment]
@pps83 

Well, it is not a hidden requirement: `simdfastpfor128` works over blocks of 128 integers. Unless you you have a multiple of 128 values, you should not call `simdfastpfor128` directly.

**Comment by lemire** [comment]
@pps83 

If you go through the factory call, then you should be fine...

```C++
IntegerCODEC &codec = *CODECFactory::getFromName("simdfastpfor128");
```

**Comment by lemire** [comment]
... because the factory wraps the codec.

**Comment by pps83** [comment]
Yes, I use it through the wrapper (but not through the codec factory, as I don't want to pull in all other codecs into my binary because of that map). I use `FastPForLib::CompositeCodec<FastPForLib::SIMDFastPFor<4>, FastPForLib::VariableByte>`, and it seems that there are "hidden" requirements: if the input buffer isn't aligned, then I get asserts: `assert(!needPaddingTo128Bits(in));`, and if I comment it out, I get different outputs.

**Comment by lemire** [comment]
> it seems that there are "hidden" requirements

You are correct. There are leftover implicit alignment restrictions. We removed them in follow-up work, but they were never lifted in this library... see...

https://github.com/lemire/FastPFor/issues/53

Pull requests are invited to solve this issue.

> When I read them back I decode them. So far, encoding fails because it seems that not only that it expects alignegment, but also produces different output depending on input alignment.

They are definitively sensitive to alignment. In fact, it is even documented in the code that you are responsible to maintain alignment prior to decoding.

Obviously, this is not desirable and should be fixed. Please see the issue I just created.
