### ISSUE TITLE
32-bit ARM support

### ISSUE THREAD

**Issue by MrSherish** [lemire/FastPFor#63]
Hey,

Is it possible to build and run the decompression on an ARM 32-bit system?
Also, how easy would it be to use 16-bit integers instead of 32 or 64?

Best

**Comment by lemire** [comment]
Some of the codecs will work for sure.

In general, you will have to do extra work to support 16-bit integers.

Please see https://github.com/lemire/streamvbyte
where 64-bit ARM is supported.


Regarded integer size, see related discussion at https://github.com/lemire/streamvbyte/issues/28

You may also want to store you integers into bitmaps... see
https://github.com/RoaringBitmap/CRoaring
