### ISSUE TITLE
How to serialize/save and load/deserialize

### ISSUE THREAD

**Issue by ruetechy** [lemire/FastPFor#71]
Hi,

I have attempted to serialize/save using the following code:
```c++
std::ofstream outfile("outfile.dat", std::ofstream::binary);
outfile.write(reinterpret_cast<const char*>(compressed_output.data() /* or &v[0] pre-C++11 */), sizeof(uint32_t) * compressed_output.size());
outfile.close();```

 I am not sure this is the right way because I am ending with a file that is larger (~2x) than what is reported by:
```c++
  std::cout << std::setprecision(3);
  std::cout << "You are using "
            << 32.0 * static_cast<double>(compressed_output.size()) /
                   static_cast<double>(mydata.size())
            << " bits per integer. " << std::endl;```

For instance, I get `You are using 9.11 bits per integer` with `96504` integers but my output file is `-rw-r--r--  1 root root 215K May 10 18:58 outfile.dat`

What am I doing wrong? Also, how would you load/deserialize from this file?

Thanks for your help.

**Comment by lemire** [comment]
What is the value of `sizeof(uint32_t) * compressed_output.size()`?

**Comment by ruetechy** [comment]
The value is `219700`

**Comment by lemire** [comment]
Hence `compressed_output.size()` is 54925. 

What is `mydata.size()`? You wrote that the program computed that `32.0 * static_cast<double>(compressed_output.size()) /  static_cast<double>(mydata.size())` is 9.11.

It should be that `mydata.size()` is about 193008. But you wrote that you had 96504 integers. 

One of these numbers is wrong.

**Comment by ruetechy** [comment]
Oh you are right! Found the issue in my code now I am getting a larger bits per integer (18.1) which is expected. Thanks!
