### ISSUE TITLE
Follow-up on #75

### ISSUE THREAD

**Issue by linuslh1996** [lemire/FastPFor#76]
Hey,
thank you for your fast answer! I took a look at the _SIMDCompressionAndIntersection_ library and at the papers. I will now call what I described with "Point-Based Access" _Random Access_, since this seems to be the common term. From what I see, the paper describes that Random Access is possible with some of the codecs. I also saw that you implemented functions like the `insert` function to insert new values into the compressed structure. I did, however, not find a clear example on how to use the library for Radom Access. If one of your codecs does support Random Access, could you provide a concrete code example on how to use it? This would be immensely helpful to me!

**Comment by lemire** [comment]
@linuslh1996  Please refer to the SIMDCompressionAndIntersection project and others repository where search and select functions have been implemented. If, after studying the code, the tests and the benchmarks, you have questions, please raise them as an issue *in the relevant repositories*.

If you rightly feel that there should be better documentation, please consider contributing pull requests improving matters.

The current expectation is that you are supposed to study the code itself. There is no further documentation beyond the research papers. We count on the community and people like you to improve matters.
