### ISSUE TITLE
Some of the functions leave gaps in output buffers

### ISSUE THREAD

**Issue by pps83** [lemire/FastPFor#99]
For my own purpose I added unit tests and I got lots of failures because some of the codecs in FastPFor leave uninitialized gaps in output buffers when encoding. Namely, these are the codecs that fail in my tests:
simdfastpfor128, simdfastpfor256, varintg8iu, imdgroupsimple_ringbuf

This is the test I use:
```
TEST(Compression, testIntegerCodec)
{
    const size_t SZ = 12345;
    const uint32_t n = 1000;
    const int diff = 10;
    std::vector<uint32_t> in(SZ, n);
    for (auto& n : in)
        n += (rand32() % (diff * 2)) - diff;
    // in is an array of random numbers in the range of [990, 1010]

    for (auto& coder : coders::allCodecs())
    {
        if (coder.name() == "Null")
            return;
        LOG("coder: %s", std::string(coder.name()).c_str());
        std::vector<uint8_t> buf8(4 * (SZ + SZ / 4), 0xaa);  // << == init to 0xaa
        std::vector<uint32_t> buf32a, buf32b;
        size_t a = coder.encode(in, buf32a);
        size_t b = coder.encode(&in[0], in.size(), buf32b);
        size_t c = coder.encode(&in[0], in.size(), &buf8[0], buf8.size());
        buf8.resize(c);
        ASSERT_EQ(a, b);
        ASSERT_EQ(a, c);
        ASSERT_EQ(buf32a, buf32b);
        ASSERT_EQ(0, memcmp(buf32a.data(), buf8.data(), c));
    }
}
```

Most codecs pass the test, but those that fail have this memory diff:
![image](https://user-images.githubusercontent.com/1614246/219432926-b94c5d34-e797-4ca7-a98b-00a6d7e036c2.png)

as you can see, those that fail, set first 8 bytes, then 8 bytes left untouched. IMO, these codecs should be fixed to set that "untouuched" memory to something.

**Comment by pps83** [comment]
Note, my `coders::allCodecs()` and `.encode` are thin wrappers over `FastPForLib::IntegerCODEC`

**Comment by pps83** [comment]
https://github.com/lemire/FastPFor/pull/100 fixes simdfastpfor128, simdfastpfor256. However, varintg8iu, imdgroupsimple_ringbuf still have the diff issue, and the output differences in deep inside the output buffer itself.

**Comment by pps83** [comment]
I did more tests, seems like `varintg8iu` leave uninitialized bytes at the end out the output buffer. In my test case, it's last 7 bytes.
In case of `simdgroupsimple_ringbuf`  I get whopping 1040 consecutive bytes uninitialized somewhere in the middle of the output buffer. Seems like a bug in `simdgroupsimple_ringbuf`.

**Comment by pps83** [comment]
Ah, so, `simdgroupsimple_ringbuf` is the same as `simdgroupsimple` except that it has that `pessimistic gap` in the middle?

**Comment by lemire** [comment]
@pps83 No. But just wait I am preparing a PR.

**Comment by lemire** [comment]
Please see https://github.com/lemire/FastPFor/pull/101

We change just turn off the pessimistic gap feature. It will slow down construction a bit. That's what I propose doing.

**Comment by pps83** [comment]
I pulled your PR locally to verify. I still get one case with a one byte gap in `simdgroupsimple` when I use 100 instead of 1000 to fill input buffer.

**Comment by lemire** [comment]
> I still get one case with a one byte gap in simdgroupsimple when I use 100 instead of 1000 to fill input buffer.

Thanks for the review. Please consider producing a pull request to trim the byte in question.
